name: Unit Tests

on:
    - push
    - fork
    - pull_request

jobs:
    tests:
        runs-on: ubuntu-latest
        name: "Unit tests for PHP ${{ matrix.php-version }} & Neo4j ${{ matrix.neo4j-version }}"
        container: ubuntu
        strategy:
            fail-fast: false
            matrix:
                php-version: ['8.1']
                neo4j-version: ['4.3', '4.4', '5.1.0']
        env:
            ENABLE_FEATURE_TEST: true
            NEO4J_VERSION: ${{ matrix.neo4j-version }}
        services:
            neo4j:
                image: neo4j:${{ matrix.neo4j-version }}
                env:
                    NEO4J_AUTH: neo4j/password
                ports:
                    - "7474:7474"
                    - "7687:7687"
        steps:
            - uses: actions/checkout@v2
            - name: Cache Composer dependencies
              uses: actions/cache@v2
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2
            - run: composer install
              shell: bash
            - run: composer test
              shell: bash
